plugins { id 'com.android.application' }

android {
    namespace 'com.luma.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.luma.app'
        minSdk 26
        targetSdk 35
        versionCode 9
        versionName '2.7'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
